name: flutter_app
description: Medical History Management Application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # Apple iOS icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # 2.0.1
flutter:
  uses-material-design: true # Android - Material Design, iOS - Cupertino Design
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/