name: flutter_app
description: Medical History Management Application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # Apple iOS icons
  flutter_storage_path: ^1.0.4
  permission_handler: ^10.4.3
  device_info_plus: ^3.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # 2.0.1
flutter:
  uses-material-design: true # Android - Material Design, iOS - Cupertino Design
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23